apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/armanruet/gitops-demo-app.git'
    targetRevision: main
    path: overlays/prod         # 👈 Prod overlay
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod             # 👈 Kubernetes "prod" namespace
  syncPolicy:
    # Often prod is manual-sync in real life.
    # To make it manual: remove the 'automated' block completely.
    automated:
      prune: true
      selfHeal: true
